echo -e "bsort100" >> cacheEviction.txt
./cache_infer.sh bsort100 bsort100  ARM lp_solve
./cache_infer.sh bsort100 crc  ARM lp_solve
./cache_infer.sh bsort100 expint  ARM lp_solve
./cache_infer.sh bsort100 fft  ARM lp_solve
./cache_infer.sh bsort100 ud  ARM lp_solve
./cache_infer.sh bsort100 statemate  ARM lp_solve
./cache_infer.sh bsort100 ludcmp  ARM lp_solve
./cache_infer.sh bsort100 matmult  ARM lp_solve
./cache_infer.sh bsort100 ns  ARM lp_solve
./cache_infer.sh bsort100 nsichneu  ARM lp_solve
echo -e "\ncrc" >> cacheEviction.txt
./cache_infer.sh crc bsort100  ARM lp_solve
./cache_infer.sh crc crc  ARM lp_solve
./cache_infer.sh crc expint  ARM lp_solve
./cache_infer.sh crc fft  ARM lp_solve
./cache_infer.sh crc ud  ARM lp_solve
./cache_infer.sh crc statemate  ARM lp_solve
./cache_infer.sh crc ludcmp  ARM lp_solve
./cache_infer.sh crc matmult  ARM lp_solve
./cache_infer.sh crc ns  ARM lp_solve
./cache_infer.sh crc nsichneu  ARM lp_solve
echo -e "\nexpint" >> cacheEviction.txt
./cache_infer.sh expint bsort100  ARM lp_solve
./cache_infer.sh expint crc  ARM lp_solve
./cache_infer.sh expint expint  ARM lp_solve
./cache_infer.sh expint fft  ARM lp_solve
./cache_infer.sh expint ud  ARM lp_solve
./cache_infer.sh expint statemate  ARM lp_solve
./cache_infer.sh expint ludcmp  ARM lp_solve
./cache_infer.sh expint matmult  ARM lp_solve
./cache_infer.sh expint ns  ARM lp_solve
./cache_infer.sh expint nsichneu  ARM lp_solve
echo -e "\nfft" >> cacheEviction.txt
./cache_infer.sh fft bsort100  ARM lp_solve
./cache_infer.sh fft crc  ARM lp_solve
./cache_infer.sh fft expint  ARM lp_solve
./cache_infer.sh fft fft  ARM lp_solve
./cache_infer.sh fft ud  ARM lp_solve
./cache_infer.sh fft statemate  ARM lp_solve
./cache_infer.sh fft ludcmp  ARM lp_solve
./cache_infer.sh fft matmult  ARM lp_solve
./cache_infer.sh fft ns  ARM lp_solve
./cache_infer.sh fft nsichneu  ARM lp_solve
echo -e "\nud" >> cacheEviction.txt
./cache_infer.sh ud bsort100  ARM lp_solve
./cache_infer.sh ud crc  ARM lp_solve
./cache_infer.sh ud expint  ARM lp_solve
./cache_infer.sh ud fft  ARM lp_solve
./cache_infer.sh ud ud  ARM lp_solve
./cache_infer.sh ud statemate  ARM lp_solve
./cache_infer.sh ud ludcmp  ARM lp_solve
./cache_infer.sh ud matmult  ARM lp_solve
./cache_infer.sh ud ns  ARM lp_solve
./cache_infer.sh ud nsichneu  ARM lp_solve
echo -e "\nstatemate" >> cacheEviction.txt
./cache_infer.sh statemate bsort100  ARM lp_solve
./cache_infer.sh statemate crc  ARM lp_solve
./cache_infer.sh statemate expint  ARM lp_solve
./cache_infer.sh statemate fft  ARM lp_solve
./cache_infer.sh statemate ud  ARM lp_solve
./cache_infer.sh statemate statemate  ARM lp_solve
./cache_infer.sh statemate ludcmp  ARM lp_solve
./cache_infer.sh statemate matmult  ARM lp_solve
./cache_infer.sh statemate ns  ARM lp_solve
./cache_infer.sh statemate nsichneu  ARM lp_solve
echo -e "\nludcmp" >> cacheEviction.txt
./cache_infer.sh ludcmp bsort100  ARM lp_solve
./cache_infer.sh ludcmp crc  ARM lp_solve
./cache_infer.sh ludcmp expint  ARM lp_solve
./cache_infer.sh ludcmp fft  ARM lp_solve
./cache_infer.sh ludcmp ud  ARM lp_solve
./cache_infer.sh ludcmp statemate  ARM lp_solve
./cache_infer.sh ludcmp ludcmp  ARM lp_solve
./cache_infer.sh ludcmp matmult  ARM lp_solve
./cache_infer.sh ludcmp ns  ARM lp_solve
./cache_infer.sh ludcmp nsichneu  ARM lp_solve
echo -e "\nmatmult" >> cacheEviction.txt
./cache_infer.sh matmult bsort100  ARM lp_solve
./cache_infer.sh matmult crc  ARM lp_solve
./cache_infer.sh matmult expint  ARM lp_solve
./cache_infer.sh matmult fft  ARM lp_solve
./cache_infer.sh matmult ud  ARM lp_solve
./cache_infer.sh matmult statemate  ARM lp_solve
./cache_infer.sh matmult ludcmp  ARM lp_solve
./cache_infer.sh matmult matmult  ARM lp_solve
./cache_infer.sh matmult ns  ARM lp_solve
./cache_infer.sh matmult nsichneu  ARM lp_solve
echo -e "\nns" >> cacheEviction.txt
./cache_infer.sh ns bsort100  ARM lp_solve
./cache_infer.sh ns crc  ARM lp_solve
./cache_infer.sh ns expint  ARM lp_solve
./cache_infer.sh ns fft  ARM lp_solve
./cache_infer.sh ns ud  ARM lp_solve
./cache_infer.sh ns statemate  ARM lp_solve
./cache_infer.sh ns ludcmp  ARM lp_solve
./cache_infer.sh ns matmult  ARM lp_solve
./cache_infer.sh ns ns  ARM lp_solve
./cache_infer.sh ns nsichneu  ARM lp_solve
echo -e "\nnsichneu" >> cacheEviction.txt
./cache_infer.sh nsichneu bsort100  ARM lp_solve
./cache_infer.sh nsichneu crc  ARM lp_solve
./cache_infer.sh nsichneu expint  ARM lp_solve
./cache_infer.sh nsichneu fft  ARM lp_solve
./cache_infer.sh nsichneu ud  ARM lp_solve
./cache_infer.sh nsichneu statemate  ARM lp_solve
./cache_infer.sh nsichneu ludcmp  ARM lp_solve
./cache_infer.sh nsichneu matmult  ARM lp_solve
./cache_infer.sh nsichneu ns  ARM lp_solve
./cache_infer.sh nsichneu nsichneu  ARM lp_solve
