
INCLS=-Isrc -I../utl/src
OBJS=obj/arch.o  obj/ARM.o  obj/DAAInstruction.o  obj/DAAInstruction_MIPS.o  obj/DAAInstruction_ARM.o obj/InstructionFormat.o  obj/InstructionType.o  obj/MIPS.o
include ../makefile.common

cleandoc:
	$(RM) -R doc/generated-doc/html

