
INCLS=-Isrc -I../cfglib/include -I../ArchitectureDependent/src -I$(XML2) -I../GlobalAttributes/src 
OBJS=obj/Logger.o obj/Utl.o obj/InstructionARM.o

include ../makefile.common


cleandoc:
	$(RM) -R doc/generated-doc/html

