
INCLS+=-Isrc -I../cfglib/include -I../utl/src -I../ArchitectureDependent/src -I$(XML2)
OBJS=obj/ARMWordsAttribute.o obj/LoopTree.o obj/SymbolTableAttribute.o obj/AddressAttribute.o  obj/MetaInstructionAttribute.o

include ../makefile.common

cleandoc:
	$(RM) -R doc/generated-doc/html

